### ISSUE TITLE
I need some help to better organize this project

### ISSUE THREAD

**Issue by lucashtm** [lucashtm/pumped-up-leaders#1]
It is a static page with css embedded inside the html file and it makes new changes painful.

**Comment by Martin271322** [comment]
hello you speak Spanish

**Comment by chris-c-thomas** [comment]
I'll place the css in an external file named 'styles.css' and link it within 'index.html' so that you can better manage the code and changes.

**Comment by lucashtm** [comment]
Thanks @simplenclean ;)

**Comment by ctbwx** [comment]
No problem man! :)

**Comment by ctbwx** [comment]
That's one killer project.

**Comment by lucashtm** [comment]
> That's one killer project.

Thanks mate! ;)
